version: '3.8'

# 开发环境 Docker Compose 配置
# 使用方法: docker compose -f docker compose.yml -f docker compose.dev.yml up

services:
  # 开发环境前端服务 - 支持热重载
  pindata-frontend-dev:
    build:
      context: ../frontend
      dockerfile: Dockerfile.dev
    container_name: pindata_frontend_dev
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - pindata-api
    restart: unless-stopped
    networks:
      - llama_network
    command: ["pnpm", "dev", "--host", "0.0.0.0"]

  # 开发环境 API 服务 - 启用调试模式
  pindata-api:
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - ../backend:/app:cached
    ports:
      - "8897:8897"
      - "5678:5678"  # 调试端口

  # 开发环境 Celery 服务
  pindata-celery:
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - ../backend:/app:cached 